### ISSUE TITLE
Invalid array index

### ISSUE THREAD

**Issue by yangxiang92** [pthrasher/c-generic-ring-buffer#6]
The macro to get the index indicating that the maximum value of the `BUF->start` and `BUF->end` could be `BUF->size`:
```C
#define nextStartIndex(BUF) ((BUF->start + 1) % (BUF->size + 1))
#define nextEndIndex(BUF) ((BUF->end + 1) % (BUF->size + 1))
```
The buffer size for the elements is `BUF->size`, which means that the max valid index of the element buffer should be `BUF->size - 1`.  But following code is trying to access `BUF->size` index at sometime, which could cause problems.
```C
#define bufferWrite(BUF, ELEM) \
  BUF->elems[BUF->end] = ELEM; \
  BUF->end = (BUF->end + 1) % (BUF->size + 1); \
  if (isBufferEmpty(BUF)) { \
    BUF->start = nextStartIndex(BUF); \
  }

#define bufferRead(BUF, ELEM) \
    ELEM = BUF->elems[BUF->start]; \
    BUF->start = nextStartIndex(BUF);
```

**Comment by karstenkoenig** [comment]
I fixed this issue in my pull request, https://github.com/pthrasher/c-generic-ring-buffer/pull/7

I've kept the BUF->SIZE field and increased the 'actual' size by 1 to allow for simpler operations when avoiding the modulo operation

**Comment by glouw** [comment]
Still an issue. The example crashes valgrinds sg-check for array bounds.

**Comment by karstenkoenig** [comment]
It does indeed for me too, but the output is not helping, it just crashes with 'impossible error happened' and the only information i can find about that error indicates the sgcheck tool isn't really working most of the time
https://bugzilla.redhat.com/show_bug.cgi?id=1552055

Also I get the same crash when just running it on a simple hello world example using printf.


Do you have a verbose output that could pinpoint an actual problem?

This is the sgcheck output for me:

```

==9216== exp-sgcheck, a stack and global array overrun detector
==9216== NOTE: This is an Experimental-Class Valgrind Tool
==9216== Copyright (C) 2003-2017, and GNU GPL'd, by OpenWorks Ltd et al.
==9216== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==9216== Command: ./test
==9216== 
exp-sgcheck: sg_main.c:2332 (sg_instrument_IRStmt): the 'impossible' happened.

host stacktrace:
==9216==    at 0x5801554A: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x58015664: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x580157E9: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x5800E499: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x58008975: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x58030FEF: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x580E9E07: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x580EA2C9: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x58033762: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x5806D85E: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)
==9216==    by 0x5807D8A0: ??? (in /usr/lib64/valgrind/exp-sgcheck-amd64-linux)

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 9216)
==9216==    at 0x40159BA: _dl_runtime_resolve_xsave (in /lib64/ld-2.27.so)
==9216==    by 0x4E54A86: (below main) (in /lib64/libc-2.27.so)

```

**Comment by glouw** [comment]
Alas, no, I got what you got.

**Comment by pthrasher** [comment]
Fixed via #7
